# **MLP**





In [390]:
import pandas as pd

dataset = pd.read_csv("https://raw.githubusercontent.com/talesjoabe/ECT2702-2020.2/master/SVM/StudentsPerformance.csv")

dataset.head()

gender race/ethnicity  ... reading score writing score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75

[5 rows x 8 columns]

In [391]:
dataset.describe()

math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

## Padronização da coluna 'race/ethnicity'

In [392]:
dataset['race/ethnicity'].value_counts()


group C    319
group D    262
group B    190
group E    140
group A     89
Name: race/ethnicity, dtype: int64

In [393]:
dataset['race/ethnicity'].replace({'group A' : 1, 'group B' : 2, 'group C' : 3, 'group D' : 4, 'group E' : 5}, inplace=True)

In [394]:
dataset['race/ethnicity'].value_counts()


3    319
4    262
2    190
5    140
1     89
Name: race/ethnicity, dtype: int64

## Padronização da coluna 'parental level of education'

In [395]:
dataset['parental level of education'].value_counts()

some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: parental level of education, dtype: int64

In [396]:
dataset['parental level of education'].replace({'some college' : 1, "associate's degree" : 2, "high school" : 3, "some high school" : 4, "bachelor's degree" : 5, "master's degree" : 6}, inplace=True)


In [397]:
dataset['parental level of education'].value_counts()

1    226
2    222
3    196
4    179
5    118
6     59
Name: parental level of education, dtype: int64

## Padronização da coluna gênero

1: Female

0: Male

In [398]:
dataset['gender'].replace({'female' : 1, 'male' : 0},inplace=True)

In [399]:
dataset.head()

gender  race/ethnicity  ...  reading score writing score
0       1               2  ...             72            74
1       1               3  ...             90            88
2       1               2  ...             95            93
3       0               1  ...             57            44
4       0               3  ...             78            75

[5 rows x 8 columns]

## Escolha dos atributos


In [400]:
dataset.corr()

gender  ...  writing score
gender                       1.000000  ...       0.301225
race/ethnicity               0.001502  ...       0.165691
parental level of education  0.020417  ...       0.055357
math score                  -0.167982  ...       0.802642
reading score                0.244313  ...       0.954598
writing score                0.301225  ...       1.000000

[6 rows x 6 columns]

In [401]:
X = dataset.loc[:,['math score', 'writing score', 'reading score']].values
y = dataset['gender'].values

## Separando entre conjuntos de treinamento e teste



In [402]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Normalização

In [403]:
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Arquitetura da rede

In [404]:
import tensorflow as tf

In [405]:
# Inicialização 
classifier = tf.keras.models.Sequential()

# Adicionando a camada de entrada e a primeira camada escondida  
classifier.add( tf.keras.layers.Dense( activation = 'relu', input_dim = 3, units = 4, kernel_initializer = 'orthogonal'))

# Adicionando a camada de saída 
classifier.add( tf.keras.layers.Dense( activation = 'sigmoid', units = 1, kernel_initializer = 'uniform'))

In [406]:
# Montando a Rede 
classifier.compile(optimizer = 'NAdam', loss = 'binary_crossentropy', metrics = ['accuracy'])

## Treinamento

In [407]:
classifier.fit(X_train, y_train, batch_size = 3, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 977us/step - loss: 0.6913 - accuracy: 0.5897
Epoch 2/200
250/250 [==============================] - 0s 936us/step - loss: 0.6858 - accuracy: 0.5820
Epoch 3/200
250/250 [==============================] - 0s 963us/step - loss: 0.6784 - accuracy: 0.6060
Epoch 4/200
250/250 [==============================] - 0s 898us/step - loss: 0.6708 - accuracy: 0.6607
Epoch 5/200
250/250 [==============================] - 0s 909us/step - loss: 0.6600 - accuracy: 0.7385
Epoch 6/200
250/250 [==============================] - 0s 991us/step - loss: 0.6508 - accuracy: 0.7871
Epoch 7/200
250/250 [==============================] - 0s 934us/step - loss: 0.6430 - accuracy: 0.7523
Epoch 8/200
250/250 [==============================] - 0s 980us/step - loss: 0.6275 - accuracy: 0.8185
Epoch 9/200
250/250 [==============================] - 0s 913us/step - loss: 0.6221 - accuracy: 0.8031
Epoch 10/200
250/250 [==============================] - 0s 983us/step - l

# Avaliação do modelo

In [408]:
y_pred = classifier.predict(X_test)

print(y_test[0:25])
print(y_pred[0:25])

[1 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 1 1 0 1 1 1 0 0]
[[0.9729008 ]
 [0.00635824]
 [0.8704618 ]
 [0.00710228]
 [0.91396546]
 [0.04628971]
 [0.87704086]
 [0.07441929]
 [0.00505704]
 [0.00702071]
 [0.12518716]
 [0.99275726]
 [0.02325964]
 [0.22078526]
 [0.9137871 ]
 [0.8617064 ]
 [0.03916165]
 [0.9307551 ]
 [0.8098184 ]
 [0.5372023 ]
 [0.28173822]
 [0.68155015]
 [0.8794794 ]
 [0.03075594]
 [0.00946739]]


In [409]:
y_pred_bin = [ ( 1 if elem > 0.5 else 0) for elem in y_pred ] 

In [410]:
import numpy as np

print(y_test[0:35])
print(y_pred_bin[0:35])
#y_pred_bin =  np.array(y_pred_bin)

[1 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 1 1 0 1 1 1 0 0 0 0 0 1 1 1 0 1 1 1]
[1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1]


### Acurácia

In [411]:
from sklearn.metrics import accuracy_score

print("Acurácia: ", accuracy_score(y_test,y_pred_bin)*100, "%"  )

Acurácia:  87.6 %


### Matriz de confusão

In [412]:


from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_bin)
print("Matrix de confusão: ")
print(cm)



Matrix de confusão: 
[[100  22]
 [  9 119]]
